version: 2 

models:
  - name: customers
    description: '{{ doc("customer_model_desc") }}'
    columns:
      - name: customerid 
        description: Primary key 
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order 

  - name: stg_customers
    description: This model cleans up customer data 
    columns:
      - name: customerid
        tests:
          - unique 
          - not_null 
     
  - name: stg_orders
    description: This model cleans up order data 
    columns: 
      - name: salesordernumber
        description: Primary key 
        tests: 
          - unique 
          - not_null 
      - name: salesorderlinestatus
        tests: 
          - acceptedvalues_adj: 
              values: ('Invoiced', 'Open order', 'Canceled')
      - name: customerid
        tests:
          - not_null
          - relationships_adj:
              to: ref('stg_customers')
              field: customerid
      

